version: "3.7"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/maizedisease
      - SPRING_DATASOURCE_USERNAME=auga
      - SPRING_DATASOURCE_PASSWORD=auga.
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    restart: always
    container_name: db
    environment:
     - POSTGRES_DB=maizedisease
     - POSTGRES_USER=auga
     - POSTGRES_PASSWORD=auga.
     - PGDATA=/var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: auga@gmail.com
      PGADMIN_DEFAULT_PASSWORD: auga
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8081:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"
volumes:
  db-data:
  pgadmin-data: