create table answers_table
(
    id                int8 generated by default as identity,
    uuid              varchar(12)  not null,
    answer_content    varchar(800) not null,
    answer_image      oid,
    answer_image_name varchar(255),
    answer_image_type varchar(255),
    created_at        timestamp    not null,
    modified_at       timestamp    not null,
    issue_id          int8         not null,
    user_id           int8         not null,
    primary key (id)
);

create table diseases_table
(
    id           int8 generated by default as identity,
    uuid         varchar(12) not null,
    disease_name varchar(200),
    primary key (id)
);
create table issues_table
(
    id                int8 generated by default as identity,
    uuid              varchar(12)   not null,
    created_at        timestamp     not null,
    crop              varchar(300),
    image_name        varchar(255),
    image_type        varchar(255),
    issue_image       oid,
    issue_status      varchar(20)   not null,
    modified_at       timestamp     not null,
    issue_name        varchar(200)  not null,
    issue_description varchar(2000) not null,
    user_id           int8          not null,
    primary key (id)
);

create table prescriptions_table
(
    id                   int8 generated by default as identity,
    uuid                 varchar(12)  not null,
    disease_prescription varchar(800) not null,
    disease_id           int8,
    primary key (id)
);

create table roles_table
(
    id   int8 generated by default as identity,
    uuid varchar(12) not null,
    name varchar(20),
    primary key (id)
);

create table symptoms_table
(
    id                  int8 generated by default as identity,
    uuid                varchar(12)  not null,
    symptom_description varchar(800) not null,
    disease_id          int8,
    primary key (id)
);

create table user_answer_dislikes_table
(
    user_id   int8 not null,
    answer_id int8 not null
);

create table user_answer_likes_table
(
    user_id   int8 not null,
    answer_id int8 not null
);

create table user_issue_dislikes_table
(
    user_id  int8 not null,
    issue_id int8 not null
);
create table user_issue_likes_table
(
    user_id  int8 not null,
    issue_id int8 not null
);

create table user_roles_table
(
    user_id int8 not null,
    role_id int8 not null
);

create table users_table
(
    id        int8 generated by default as identity,
    uuid      varchar(12)  not null,
    email     varchar(150) not null,
    fist_name varchar(90)  not null,
    is_active boolean,
    last_name varchar(90)  not null,
    password  varchar(200) not null,
    primary key (id)
);

alter table if exists answers_table
    add constraint UK_cg6bv1e34ik7sp08wlld3rxnb unique (uuid);

alter table if exists diseases_table
    add constraint UK_bsfm21bbnu0bgsem6yivf71yx unique (uuid);

alter table if exists diseases_table
    add constraint UK_2s0ai4hijcce5i148upvqw20x unique (disease_name);

alter table if exists issues_table
    add constraint UK_tm5we5mu92w1eupkbtx2xyut unique (issue_status);

alter table if exists issues_table
    add constraint UK_2f2ic4601jenu3kyjptdhyr3g unique (uuid);

alter table if exists prescriptions_table
    add constraint UK_8pfld9eellj736xreyiwwadqm unique (uuid);

alter table if exists prescriptions_table
    add constraint UK_ffbuc1as7gro4a4x0kjjcrebr unique (disease_prescription);

alter table if exists roles_table
    add constraint UK_m7lskxh792uppbobqegc9vwp unique (name);

alter table if exists roles_table
    add constraint UK_69f4lmqes948pbpps04wfe4px unique (uuid);

alter table if exists symptoms_table
    add constraint UK_cugy0d6ymx6d2526rwgcprb6a unique (uuid);

alter table if exists symptoms_table
    add constraint UK_chk02s5bglfjlvjhr18r3k2v4 unique (symptom_description);

alter table if exists users_table
    add constraint UK_iatnk4g225rvfbddoj8aqa2wy unique (uuid);

alter table if exists users_table
    add constraint UK_k9gbvc9xvagimmj1y060txmha unique (email);

alter table if exists answers_table
    add constraint FKevd7qeuy73josa0a6ohwn9wwe
    foreign key (issue_id)
    references issues_table;

alter table if exists answers_table
    add constraint FKidk4oaphov3fr1q0xm0x1lkg3
    foreign key (user_id)
    references users_table;

alter table if exists issues_table
    add constraint FK5b1tt8akq5ekai7m0s4jx6ouf
    foreign key (user_id)
    references users_table;

alter table if exists prescriptions_table
    add constraint FKjqsdliptiolpdnt0sqkw28gt3
    foreign key (disease_id)
    references diseases_table;

alter table if exists symptoms_table
    add constraint FKdbv8ed1t4sxmg9a3ql8n4aj3a
    foreign key (disease_id)
    references diseases_table;

alter table if exists user_answer_dislikes_table
    add constraint FKqekea684wjw2lpbwx2wpbyffx
    foreign key (answer_id)
    references users_table;

alter table if exists user_answer_dislikes_table
    add constraint FKlnqg93lx40v2gjyujl4c8kuql
    foreign key (user_id)
    references answers_table;

alter table if exists user_answer_likes_table
    add constraint FKaj0uepr3yjsymfbv0baybayi4
    foreign key (answer_id)
    references users_table;

alter table if exists user_answer_likes_table
    add constraint FKi7t6ltip3gq4qo23ammt2fdlt
    foreign key (user_id)
    references answers_table;

alter table if exists user_issue_dislikes_table
    add constraint FK985cuv6ork880akamf5mymi19
    foreign key (issue_id)
    references users_table;

alter table if exists user_issue_dislikes_table
    add constraint FKhaakqfi09daye68tckyse4k00
    foreign key (user_id)
    references issues_table;

alter table if exists user_issue_likes_table
    add constraint FKn4nuwjhuriudtcpeli3xir6q4
    foreign key (issue_id)
    references users_table;

alter table if exists user_issue_likes_table
    add constraint FKmicaaprdsgndlnj2xtqnuj1x
    foreign key (user_id)
    references issues_table;

alter table if exists user_roles_table
    add constraint FK3o86medq7lraupt4skdk5htc2
    foreign key (role_id)
    references roles_table;

alter table if exists user_roles_table
    add constraint FKl3vacgjg4x55hg4vxlftl6eas
    foreign key (user_id)
    references users_table;