CREATE TABLE answers_table
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid           VARCHAR(12)                             NOT NULL,
    answer_content VARCHAR(800)                            NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    modified_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    issue_id       BIGINT                                  NOT NULL,
    user_id        BIGINT                                  NOT NULL,
    CONSTRAINT pk_answers_table PRIMARY KEY (id)
);

CREATE TABLE diseases_table
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid         VARCHAR(12)                             NOT NULL,
    disease_name VARCHAR(200),
    CONSTRAINT pk_diseases_table PRIMARY KEY (id)
);

CREATE TABLE issues_table
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid              VARCHAR(12)                             NOT NULL,
    issue_name        VARCHAR(200)                            NOT NULL,
    issue_description VARCHAR(2000)                           NOT NULL,
    crop              VARCHAR(300),
    created_at        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    modified_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    issue_image       OID,
    image_name        VARCHAR(255),
    image_type        VARCHAR(255),
    user_id           BIGINT                                  NOT NULL,
    CONSTRAINT pk_issues_table PRIMARY KEY (id)
);

CREATE TABLE prescriptions_table
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid                 VARCHAR(12)                             NOT NULL,
    disease_prescription VARCHAR(800)                            NOT NULL,
    disease_id           BIGINT,
    CONSTRAINT pk_prescriptions_table PRIMARY KEY (id)
);

CREATE TABLE roles_table
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid VARCHAR(12)                             NOT NULL,
    name VARCHAR(20),
    CONSTRAINT pk_roles_table PRIMARY KEY (id)
);

CREATE TABLE symptoms_table
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid                VARCHAR(12)                             NOT NULL,
    symptom_description VARCHAR(800)                            NOT NULL,
    disease_id          BIGINT,
    CONSTRAINT pk_symptoms_table PRIMARY KEY (id)
);

CREATE TABLE user_answer_dislikes_table
(
    answer_id BIGINT NOT NULL,
    user_id   BIGINT NOT NULL,
    CONSTRAINT pk_user_answer_dislikes_table PRIMARY KEY (answer_id, user_id)
);

CREATE TABLE user_answer_likes_table
(
    answer_id BIGINT NOT NULL,
    user_id   BIGINT NOT NULL,
    CONSTRAINT pk_user_answer_likes_table PRIMARY KEY (answer_id, user_id)
);

CREATE TABLE user_issue_dislikes_table
(
    issue_id BIGINT NOT NULL,
    user_id  BIGINT NOT NULL,
    CONSTRAINT pk_user_issue_dislikes_table PRIMARY KEY (issue_id, user_id)
);

CREATE TABLE user_issue_likes_table
(
    issue_id BIGINT NOT NULL,
    user_id  BIGINT NOT NULL,
    CONSTRAINT pk_user_issue_likes_table PRIMARY KEY (issue_id, user_id)
);

CREATE TABLE user_roles_table
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_user_roles_table PRIMARY KEY (role_id, user_id)
);

CREATE TABLE users_table
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid      VARCHAR(12)                             NOT NULL,
    fist_name VARCHAR(90)                             NOT NULL,
    last_name VARCHAR(90)                             NOT NULL,
    email     VARCHAR(150)                            NOT NULL,
    password  VARCHAR(200)                            NOT NULL,
    is_active BOOLEAN,
    CONSTRAINT pk_users_table PRIMARY KEY (id)
);

ALTER TABLE answers_table
    ADD CONSTRAINT uc_answers_table_uuid UNIQUE (uuid);

ALTER TABLE diseases_table
    ADD CONSTRAINT uc_diseases_table_disease_name UNIQUE (disease_name);

ALTER TABLE diseases_table
    ADD CONSTRAINT uc_diseases_table_uuid UNIQUE (uuid);

ALTER TABLE issues_table
    ADD CONSTRAINT uc_issues_table_uuid UNIQUE (uuid);

ALTER TABLE prescriptions_table
    ADD CONSTRAINT uc_prescriptions_table_disease_prescription UNIQUE (disease_prescription);

ALTER TABLE prescriptions_table
    ADD CONSTRAINT uc_prescriptions_table_uuid UNIQUE (uuid);

ALTER TABLE roles_table
    ADD CONSTRAINT uc_roles_table_uuid UNIQUE (uuid);

ALTER TABLE symptoms_table
    ADD CONSTRAINT uc_symptoms_table_symptom_description UNIQUE (symptom_description);

ALTER TABLE symptoms_table
    ADD CONSTRAINT uc_symptoms_table_uuid UNIQUE (uuid);

ALTER TABLE users_table
    ADD CONSTRAINT uc_users_table_email UNIQUE (email);

ALTER TABLE users_table
    ADD CONSTRAINT uc_users_table_uuid UNIQUE (uuid);

ALTER TABLE answers_table
    ADD CONSTRAINT FK_ANSWERS_TABLE_ON_ISSUE FOREIGN KEY (issue_id) REFERENCES issues_table (id);

ALTER TABLE answers_table
    ADD CONSTRAINT FK_ANSWERS_TABLE_ON_USER FOREIGN KEY (user_id) REFERENCES users_table (id);

ALTER TABLE issues_table
    ADD CONSTRAINT FK_ISSUES_TABLE_ON_USER FOREIGN KEY (user_id) REFERENCES users_table (id);

ALTER TABLE prescriptions_table
    ADD CONSTRAINT FK_PRESCRIPTIONS_TABLE_ON_DISEASE FOREIGN KEY (disease_id) REFERENCES diseases_table (id);

ALTER TABLE symptoms_table
    ADD CONSTRAINT FK_SYMPTOMS_TABLE_ON_DISEASE FOREIGN KEY (disease_id) REFERENCES diseases_table (id);

ALTER TABLE user_answer_dislikes_table
    ADD CONSTRAINT fk_useansdistab_on_answer_entity FOREIGN KEY (user_id) REFERENCES answers_table (id);

ALTER TABLE user_answer_dislikes_table
    ADD CONSTRAINT fk_useansdistab_on_user_entity FOREIGN KEY (answer_id) REFERENCES users_table (id);

ALTER TABLE user_answer_likes_table
    ADD CONSTRAINT fk_useansliktab_on_answer_entity FOREIGN KEY (user_id) REFERENCES answers_table (id);

ALTER TABLE user_answer_likes_table
    ADD CONSTRAINT fk_useansliktab_on_user_entity FOREIGN KEY (answer_id) REFERENCES users_table (id);

ALTER TABLE user_issue_dislikes_table
    ADD CONSTRAINT fk_useissdistab_on_issue_entity FOREIGN KEY (user_id) REFERENCES issues_table (id);

ALTER TABLE user_issue_dislikes_table
    ADD CONSTRAINT fk_useissdistab_on_user_entity FOREIGN KEY (issue_id) REFERENCES users_table (id);

ALTER TABLE user_issue_likes_table
    ADD CONSTRAINT fk_useissliktab_on_issue_entity FOREIGN KEY (user_id) REFERENCES issues_table (id);

ALTER TABLE user_issue_likes_table
    ADD CONSTRAINT fk_useissliktab_on_user_entity FOREIGN KEY (issue_id) REFERENCES users_table (id);

ALTER TABLE user_roles_table
    ADD CONSTRAINT fk_useroltab_on_role FOREIGN KEY (role_id) REFERENCES roles_table (id);

ALTER TABLE user_roles_table
    ADD CONSTRAINT fk_useroltab_on_user_entity FOREIGN KEY (user_id) REFERENCES users_table (id);